from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from dataclasses import asdict, dataclass
from pathlib import Path


BACKEND_ROOT = Path(__file__).resolve().parents[1]
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from app.auth.models import ROLE_LABELS, ROLE_PERMISSIONS, Role, UserPublic
from app.collab.models import TextMessageRequest
from app.collab.service import CollaborationService
from app.collab.store import create_collaboration_store
from app.config import Settings
from app.voice_agent.models import OrchestratorResult
from scripts.init_collab_event_store import init_event_store
from scripts.target_readiness import run_target_readiness


@dataclass
class LocalRuntimeBootstrapReport:
    env_path: str
    workspace_path: str
    collab_sqlite_path: str
    event_store_ready: bool
    target_readiness_status: str
    target_readiness_score: int
    next_command: str
    force: bool = False
    demo_seeded: bool = False


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate a local VoiceOps runtime env that connects a git workspace and SQLite event store.",
    )
    parser.add_argument(
        "--env-file",
        type=Path,
        default=BACKEND_ROOT / ".env.local",
        help="Local env file to write. Defaults to backend/.env.local.",
    )
    parser.add_argument(
        "--workspace",
        type=Path,
        default=BACKEND_ROOT.parent,
        help="Absolute local git repository VoiceOps may inspect/edit.",
    )
    parser.add_argument(
        "--collab-sqlite",
        type=Path,
        default=BACKEND_ROOT / "data" / "collaboration.local.sqlite3",
        help="SQLite collaboration event-store path.",
    )
    parser.add_argument("--force", action="store_true", help="Overwrite an existing env file.")
    parser.add_argument("--replace-event-store", action="store_true", help="Replace an existing local SQLite event store.")
    parser.add_argument("--seed-demo-room", action="store_true", help="Seed the main room with a tiny demo timeline and pending patch.")
    parser.add_argument(
        "--allow-non-git-workspace",
        action="store_true",
        help="Allow a workspace without .git. Intended only for UI wiring smoke tests.",
    )
    parser.add_argument("--json", action="store_true", help="Print a machine-readable report.")
    return parser


def bootstrap_local_runtime(
    *,
    env_file: Path,
    workspace: Path,
    collab_sqlite: Path,
    force: bool = False,
    replace_event_store: bool = False,
    allow_non_git_workspace: bool = False,
    seed_demo_room: bool = False,
) -> LocalRuntimeBootstrapReport:
    workspace = workspace.expanduser().resolve()
    env_file = env_file.expanduser().resolve()
    collab_sqlite = collab_sqlite.expanduser().resolve()
    _validate_workspace(workspace, allow_non_git=allow_non_git_workspace)
    if env_file.exists() and not force:
        raise ValueError(f"{env_file} already exists; pass --force to overwrite")
    env_file.parent.mkdir(parents=True, exist_ok=True)
    collab_sqlite.parent.mkdir(parents=True, exist_ok=True)

    event_store = _ensure_event_store(collab_sqlite, replace=replace_event_store)
    env_file.write_text(_env_text(workspace=workspace, collab_sqlite=collab_sqlite), encoding="utf-8")
    os.chmod(env_file, 0o644)
    demo_seeded = _seed_demo_room(env_file=env_file, workspace=workspace) if seed_demo_room else False
    readiness = run_target_readiness(env_file=env_file)
    return LocalRuntimeBootstrapReport(
        env_path=str(env_file),
        workspace_path=str(workspace),
        collab_sqlite_path=str(collab_sqlite),
        event_store_ready=bool(event_store["ready"]),
        target_readiness_status=readiness.status,
        target_readiness_score=readiness.score,
        next_command=f"python scripts/target_readiness.py --env-file {env_file} --json",
        force=force,
        demo_seeded=demo_seeded,
    )


def _env_text(*, workspace: Path, collab_sqlite: Path) -> str:
    data_dir = collab_sqlite.parent
    return f"""# Generated by scripts/bootstrap_local_runtime.py.
DEPLOYMENT_ENVIRONMENT=local
DEBUG=false
VOICEOPS_WORKSPACE={workspace}

COLLAB_STORE_BACKEND=sqlite
COLLAB_SQLITE_PATH={collab_sqlite}
SPEAKER_STORE_BACKEND=sqlite
SPEAKER_SQLITE_PATH={data_dir / 'speakers.local.sqlite3'}
AGENT_RUNS_PATH={data_dir / 'agent_runs.local.json'}
AGENT_LLM_ROUTES_PATH={data_dir / 'agent_llm_routes.local.json'}
LONG_MEMORY_PATH={data_dir / 'long_memory.local.json'}
RAG_INDEX_PATH={data_dir / 'rag_index.local.json'}
LLM_CONNECTION_STORE_PATH={data_dir / 'llm_connections.local.json'}
EXTERNAL_AGENT_STORE_PATH={data_dir / 'external_agent_credentials.local.json'}
DEMO_EVIDENCE_PATH={BACKEND_ROOT / 'data' / 'demo_evidence.json'}

LLM_PROVIDER=mock
STT_PROVIDER=mock
SPEAKER_PROVIDER=mock
TTS_PROVIDER=mock
TTS_ON_VOICE=false
GITHUB_PR_CREATION_ENABLED=false
"""


def _ensure_event_store(collab_sqlite: Path, *, replace: bool) -> dict:
    if collab_sqlite.exists() and not replace:
        settings = Settings(collab_store_backend="sqlite", collab_sqlite_path=collab_sqlite)
        from app.collab.event_store_readiness import build_event_store_readiness

        readiness = build_event_store_readiness(settings)
        return {
            "path": str(collab_sqlite),
            "created": False,
            "replaced": False,
            "ready": readiness.ready,
            "event_count": readiness.event_count,
            "stream_count": readiness.stream_count,
            "checks": [check.model_dump(mode="json") for check in readiness.checks],
            "warnings": readiness.warnings,
        }
    return init_event_store(collab_sqlite, replace=replace)


def _seed_demo_room(*, env_file: Path, workspace: Path) -> bool:
    settings = Settings(_env_file=env_file)
    service = CollaborationService(
        create_collaboration_store(settings),
        agent_display_name=settings.agent_display_name,
        agent_initials=settings.agent_initials,
        agent_wake_words=settings.agent_wake_words,
    )
    room_id = "main"
    if service.list_messages(room_id, limit=1):
        return False

    priya = _demo_user("user-priya", "priya@voiceops.dev", "Priya Nair", "PN", Role.ON_CALL)
    sam = _demo_user("user-admin", "admin@voiceops.dev", "Sam Ortiz", "SO", Role.ADMIN)
    service.update_room_workspace(room_id, str(workspace))
    service.add_user_message(
        room_id,
        priya,
        TextMessageRequest(text="We decided to keep the fix local and review app.py before handoff.", source="demo_seed"),
    )
    service.add_user_message(
        room_id,
        sam,
        TextMessageRequest(text="Action item: confirm the /health endpoint and tests before sharing the demo.", source="demo_seed"),
    )
    service.add_agent_message(
        room_id,
        "I found the sandbox repo and prepared an approval-first health-check patch.",
        metadata={"source": "demo_seed"},
    )
    app_py = workspace / "app.py"
    service.add_action(
        room_id,
        priya,
        OrchestratorResult(
            executed=False,
            pending_approval=True,
            action="patch",
            summary="Approve sandbox health-check patch for app.py.",
            files_changed=["app.py"],
            approval={"diff": "demo proposal: keep /health returning {'status': 'ok'}"},
            approval_payload={
                "kind": "patch",
                "files": {"app.py": app_py.read_text(encoding="utf-8") if app_py.exists() else ""},
                "test_command": "python -m pytest -q",
            },
        ),
    )
    return True


def _demo_user(user_id: str, email: str, name: str, initials: str, role: Role) -> UserPublic:
    return UserPublic(
        id=user_id,
        email=email,
        name=name,
        initials=initials,
        role=role,
        role_label=ROLE_LABELS[role],
        permissions=sorted(ROLE_PERMISSIONS[role]),
    )


def _validate_workspace(workspace: Path, *, allow_non_git: bool) -> None:
    if not workspace.is_absolute():
        raise ValueError("workspace must be an absolute path")
    if not workspace.exists() or not workspace.is_dir():
        raise ValueError("workspace must exist and be a directory")
    if allow_non_git:
        return
    result = subprocess.run(
        ["git", "rev-parse", "--is-inside-work-tree"],
        cwd=workspace,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        check=False,
    )
    if result.returncode != 0 or result.stdout.strip() != "true":
        raise ValueError("workspace must be a local git repository; pass --allow-non-git-workspace only for UI smoke tests")


def print_text_report(report: LocalRuntimeBootstrapReport) -> None:
    print("VoiceOps local runtime env generated")
    print(f"- env: {report.env_path}")
    print(f"- workspace: {report.workspace_path}")
    print(f"- event store: {report.collab_sqlite_path}")
    print(f"- demo timeline: {'seeded' if report.demo_seeded else 'unchanged'}")
    print(f"- target readiness: {report.target_readiness_status} ({report.target_readiness_score}%)")
    print(f"- next: {report.next_command}")


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        report = bootstrap_local_runtime(
            env_file=args.env_file,
            workspace=args.workspace,
            collab_sqlite=args.collab_sqlite,
            force=args.force,
            replace_event_store=args.replace_event_store,
            allow_non_git_workspace=args.allow_non_git_workspace,
            seed_demo_room=args.seed_demo_room,
        )
    except (OSError, ValueError) as exc:
        if args.json:
            print(json.dumps({"status": "failed", "error": str(exc)}, indent=2))
        else:
            print(f"error: {exc}", file=sys.stderr)
        return 2
    if args.json:
        print(json.dumps({"status": "ok", **asdict(report)}, indent=2))
    else:
        print_text_report(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
